version: 2
updates:
  # Update to newer version of GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update to newer NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

    # https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/manage-your-dependency-security/controlling-dependencies-updated#allowing-specific-dependencies-to-be-updated
    allow:
      # the allow key is needed so that the ignore key below works
      - dependency-type: "all"
    ignore:
      - dependency-name: "FSharp.Core"


  # Update to newer NPM dependencies
  - package-ecosystem: "npm"
    directory: "/Tests/"
    schedule:
      interval: "weekly"